name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt install cppcheck astyle clang gcc cmake
    - name: Run test script
      run: ./run.sh -DCHECK_CODE=ON -DFORMAT_CODE=ON
